add root command

diff --git a/sunbeam-extension b/sunbeam-extension
--- a/sunbeam-extension
+++ b/sunbeam-extension
@@ -1,20 +1,9 @@
 #!/bin/bash
 
-# check for dependencies
-
-if ! command -v bkt &> /dev/null; then
-    echo "bkt could not be found"
-    exit 1
-fi
-
-if ! command -v bw &> /dev/null; then
-    echo "bw could not be found"
-    exit 1
-fi
-
 if [ $# -eq 0 ]; then
     sunbeam query -n '{
         title: "Bitwarden Vault",
+        root: "list-passwords",
         commands: [
             {
                 name: "list-passwords",
@@ -24,6 +13,17 @@ if [ $# -eq 0 ]; then
         ]
     }'
     exit 0
+fi
+
+# check for dependencies
+if ! command -v bkt &> /dev/null; then
+    echo "bkt could not be found"
+    exit 1
+fi
+
+if ! command -v bw &> /dev/null; then
+    echo "bw could not be found"
+    exit 1
 fi
 
 COMMAND=$(echo "$1" | sunbeam query -r '.command')
